import BankDatasetPlotResults
import DiabeticDatasetPlotResults
import HTRUDatasetPlotReslts


BankDatasetPlotResults.plotResults()
DiabeticDatasetPlotResults.plotResults()
HTRUDatasetPlotReslts.plotResults()